In [3]:
import torch

In [5]:
#zerod
tensor0d = torch.tensor(1)
print(tensor0d)



tensor(1)


In [7]:
#1d
tensor1d = torch.tensor([1,2,3])
print(tensor1d)

tensor([1, 2, 3])


In [19]:
#2d
tensor2d = torch.tensor([[1,2],[3,4], [5,6]])
print(tensor2d)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [11]:
#3d
tensor3d = torch.tensor([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(tensor3d[0,0,0])

tensor(1)


In [15]:
#types
print(tensor1d.dtype)
floatvec = torch.tensor([1.0,2.0,3.0])
print(floatvec)#
print(floatvec.dtype)

torch.int64
tensor([1., 2., 3.])
torch.float32


In [39]:
#other ops
tensor2d1 = torch.tensor([[1,2,3],[4,5,6]])
print(tensor2d1.shape)
print(tensor2d1)
print(tensor2d1.reshape(3,2))
print(tensor2d1.view(3,2)) #works like reshape

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [47]:
#vector ops
print(tensor2d1)
print(tensor2d1.T)
print(tensor2d1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [45]:
print(tensor2d1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [59]:
print(tensor2d1.matmul (tensor2d1.T))
print(tensor2d1 @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)